---
- name: playbook
  hosts: myserver
  become: yes
  become_method: sudo

  collections:
    - community.mysql

  vars:
    app_dir: /home/ybaddi/app
    proj_dir: /project
    db_host: "{{ lookup('env', 'db_host') | default('127.0.0.1', true) }}"
    mysql_db: project
    mysql_table: feature_flag
    mysql_app_user: ybaddi
    mysql_app_password: "Qwerty@1"
    mysql_socket: /var/run/mysqld/mysqld.sock

  tasks:
    - name: Update and install packages
      apt:
        name:
#          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - nodejs
          - npm
          - nginx
          - mysql-server
          - mysql-client
          - python3-pymysql
        state: present
        update_cache: yes
        
    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        
    - name: Add Docker repository
      apt_repository:
        repo: >
          deb [arch=amd64] https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present
    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
        
    - name: Copy build file
      copy:
        src: "{{proj_dir}}/dist"
        dest: "{{ app_dir }}"
        
    - name: Copy package-lock.json file
      copy:
        src: "{{proj_dir}}/package-lock.json"
        dest: "{{ app_dir }}"
        
        
    - name: Copy public file
      copy:
        src: "{{proj_dir}}/public"
        dest: "{{ app_dir }}"
        
    - name: Copy docker-compose.yaml file
      copy:
        src: "{{proj_dir}}/docker-compose.yaml"
        dest: "{{ app_dir }}"
    - name: Copy docker file
      copy:
        src: "{{proj_dir}}/Dockerfile"
        dest: "{{ app_dir }}"

    - name: build coffee app image
      shell: docker-compose build
      args:
        chdir: "{{ app_dir }}"
        
    - name: start coffee app container
      shell: docker-compose up -d
      args:
        chdir: "{{ app_dir }}"
        
    
    - name: Allow  HTTP on port 80
      shell: "sudo iptables -I INPUT -p tcp --dport 80 -j ACCEPT"

    - name: Configure Nginx reverse proxy
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80;
              server_name _;
              location / {
                  proxy_pass http://127.0.0.1:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }
          }

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

