---
- name: playbook
  hosts: myserver
  become: yes
  become_method: sudo


  collections:
   - community.mysql


  vars:
   app_dir: /home/ybaddi/app
   proj_dir: /project
   monitoring_dir: /monitoring
   db_host: "{{ lookup('env', 'db_host') | default('127.0.0.1', true) }}"
   mysql_db: project
   mysql_table: feature_flag
   mysql_app_user: ybaddi
   mysql_app_password: "Qwerty@1"
   mysql_socket: /var/run/mysqld/mysqld.sock


  tasks:
   - name: Update and install packages
     apt:
       name:
         - ca-certificates
         - curl
         - gnupg
         - lsb-release
         - nginx
       state: present
       update_cache: yes


   - name: Add Docker’s official GPG key
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present


   - name: Add Docker repository
     apt_repository:
       repo: >
         deb [arch=amd64] https://download.docker.com/linux/ubuntu
        {{ ansible_distribution_release }} stable
       state: present
   - name: Install Docker Engine
     apt:
       name:
         - docker-ce
         - docker-ce-cli
         - containerd.io
         - docker-compose-plugin
       state: latest
       update_cache: yes


   - name: Ensure Docker service is running
     service:
       name: docker
       state: started
       enabled: yes


   - name: Add current user to docker group
     user:
       name: "{{ ansible_user }}"
       groups: docker
       append: yes


   - name: Install loki plugin for docker
     shell: docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions


   - name: Set Docker daemon
     copy:
       dest: /etc/docker/daemon.json
       content: |
         {
          "log-driver": "loki",
          "log-opts": {
            "loki-url": "http://localhost:3100/loki/api/v1/push",
            "loki-batch-size": "400",
          }
         }


   - name: Restart docker
     service:
       name: docker
       state: restarted


   - name: Copy monitoring folder
     copy:
       src: "./monitoring"
       dest: "{{ monitoring }}"


   - name: Copy monitoring docker-compose
     copy:
       src: "./monitor-docker-compose.yaml"
       dest: "{{ monitoring }}/docker-compose.yaml"


   - name: Build grafana and loki images image
     shell: docker-compose build
     args:
       chdir: "{{ monitoring }}"


   - name: Start grafana and loki containers
     shell: docker-compose up -d
     args:
       chdir: "{{ monitoring }}"


   - name: Copy build file
     copy:
       src: "{{proj_dir}}/dist"
       dest: "{{ app_dir }}"


   - name: Copy package-lock.json file
     copy:
       src: "{{proj_dir}}/package-lock.json"
       dest: "{{ app_dir }}"


   - name: Copy public file
     copy:
       src: "{{proj_dir}}/public"
       dest: "{{ app_dir }}"


   - name: Copy docker-compose.yaml file
     copy:
       src: "{{proj_dir}}/docker-compose.yaml"
       dest: "{{ app_dir }}"


   - name: Copy docker file
     copy:
       src: "{{proj_dir}}/Dockerfile"
       dest: "{{ app_dir }}"


   - name: build coffee app image
     shell: docker-compose build
     args:
       chdir: "{{ app_dir }}"


   - name: start coffee app container
     shell: docker-compose up -d
     args:
       chdir: "{{ app_dir }}"
  
   - name: Allow  HTTP on port 80
     shell: "sudo iptables -I INPUT -p tcp --dport 80 -j ACCEPT"
  
   - name: Configure Nginx reverse proxy
     copy:
       src: "{{proj_dir}}/nginx.conf"
       dest: /etc/nginx/sites-available/default


   - name: Restart Nginx
     service:
       name: nginx
       state: restarted
  
   - name: Create .env file from GitHub Secret
     copy:
       dest: "{{ proj_dir }}/infra-deployment/.env"
       content: |
         # This file is created by Ansible
         MYSQL_PASSWORD={{ mysql_app_password }}
         MYSQL_DATABASE=coffee_shop
         MYSQL_USER=root


   - name: Build and start Monitoring Stack
     shell: docker compose -f monitor-docker-compose.yaml up -d --build
     args:
       chdir: "{{ proj_dir }}/infra-deployment"


   - name: Build and start Application Stack
     shell: docker compose -f docker-compose.yml up -d --build
     args:
       chdir: "{{ proj_dir }}/infra-deployment"