---
- name: playbook
  hosts: all

  collections:
    - community.mysql

  vars:
    proj_dir: /project
    app_dir: ~/deployment/coffeeApp
    loki_dir: ~/deployment/monitoring/loki
    grafana_dir: ~/deployment/monitoring/grafana
    deployment: deployment
    nginx_path: ~/deployment/nginx
    monitoring_dir: ~/deployment/monitoring
    db_host: "{{ lookup('env', 'db_host') | default('127.0.0.1', true) }}"
    mysql_db: project
    mysql_table: feature_flag
    mysql_app_user: ybaddi
    mysql_app_password: "Qwerty@1"
    mysql_socket: /var/run/mysqld/mysqld.sock

  tasks:
    - name: Copy deployment folder
      copy:
        src: "./deployment"
        dest: "~"

    - name: Enable Loki Docker plugin
      community.docker.docker_plugin:
        plugin_name: grafana/loki-docker-driver:latest
        alias: loki
        state: enable

    - name: Create a Docker network
      community.docker.docker_network:
        name: app-network
        driver: bridge
        state: present

    - name: Build Loki app docker image
      community.docker.docker_image:
        name: loki
        build:
          path: "{{ loki_dir }}"
        source: build
        force_source: yes

    - name: Remove existing loki container if present
      community.docker.docker_container:
        name: loki
        state: absent
        force_kill: yes

    - name: Run loki Docker container
      community.docker.docker_container:
        name: loki
        image: loki
        state: started
        networks:
          - name: app-network
        ports:
          - "3100:3100"
        restart_policy: always
        log_driver: "loki"
        log_options:
          loki-url: "http://localhost:3100/loki/api/v1/push"
          loki-batch-size: "400"

    - name: Build Docker image
      community.docker.docker_image:
        name: nginx
        build:
          path: "{{ nginx_path }}"
        source: build
        force_source: yes

    - name: Remove existing nginx container if present
      community.docker.docker_container:
        name: nginx
        state: absent
        force_kill: yes

    - name: Run Docker container
      community.docker.docker_container:
        name: nginx
        image: nginx
        state: started
        networks:
          - name: app-network
        ports:
          - "80:80"
        restart_policy: always
        log_driver: "loki"
        log_options:
          loki-url: "http://localhost:3100/loki/api/v1/push"
          loki-batch-size: "400"

    - name: Build coffee app docker image
      community.docker.docker_image:
        name: coffee-app
        build:
          path: "{{ app_dir }}"
        source: build
        force_source: yes

    - name: Remove existing coffee app container if present
      community.docker.docker_container:
        name: coffee-app
        state: absent
        force_kill: yes

    - name: Run Coffee-app Docker container
      community.docker.docker_container:
        name: coffee-app
        image: coffee-app
        state: started
        networks:
          - name: app-network
        restart_policy: always
        log_driver: "loki"
        log_options:
          loki-url: "http://localhost:3100/loki/api/v1/push"
          loki-batch-size: "400"

    - name: Build Grafana app docker image
      community.docker.docker_image:
        name: grafana
        build:
          path: "{{ grafana_dir }}"
        source: build
        force_source: yes

    - name: Remove existing Grafana container if present
      community.docker.docker_container:
        name: grafana2
        state: absent
        force_kill: yes

    - name: Run grafana Docker container
      community.docker.docker_container:
        name: grafana2
        image: grafana
        state: started
        networks:
          - name: app-network
        restart_policy: always
        log_driver: "loki"
        log_options:
          loki-url: "http://localhost:3100/loki/api/v1/push"
          loki-batch-size: "400"
